export const DUMMY_APPOINTMENTS = [
    {
        id: 1,
        name: "Bamania Rudresh Vinaychandra",
        phoneNumber: "9876543210",
        appointmentDate: "2026-06-20",
        appointmentTime: "10:00 AM",
        category: "Regular",
        paymentMethod: "Pay from Home (Online via UPI)",
        fee: 500,
        symptoms: "Mild headache and fever since 2 days",
        status: "Pending",
        feePaid: false,
        bookedDate: "2026-06-19",
    },
    {
        id: 2,
        name: "Bhargav Solanki",
        phoneNumber: "9123456789",
        appointmentDate: "2026-06-22",
        appointmentTime: "11:30 AM",
        category: "Emergency",
        paymentMethod: "Pay at Clinic (Cash/UPI at Desk)",
        fee: 1000,
        symptoms: "Severe abdominal pain and vomiting",
        status: "Completed",
        feePaid: true,
        bookedDate: "2026-06-20",
    },
    {
        id: 3,
        name: "Yash Bamania",
        phoneNumber: "8888888888",
        appointmentDate: "2026-06-23",
        appointmentTime: "02:00 PM",
        category: "Regular",
        paymentMethod: "Pay from Home (Online via UPI)",
        fee: 500,
        symptoms: "Persistent cough for 5 days",
        status: "Cancelled",
        feePaid: false,
        bookedDate: "2026-06-19",
    },
    {
        id: 4,
        name: "Ronak",
        phoneNumber: "9999999999",
        appointmentDate: "2026-06-28",
        appointmentTime: "03:30 PM",
        category: "Regular",
        paymentMethod: "Pay at Clinic (Cash/UPI at Desk)",
        fee: 500,
        symptoms: "Regular checkup and blood pressure monitoring",
        status: "Completed",
        feePaid: true,
        bookedDate: "2026-06-28",
    },
];

export const DOCTOR_DUMMY_LOGIN = {
    email: "doctor@carefirst.com",
    password: "doctor123",
    name: "Dr. Riyaz",
    specialization: "General Physician",
    clinicName: "CareFirst Clinic",
};
